# Permalinks
permalink:           pretty

# Setup
title:               Matthew DiIulio
tagline:             Insights from a developing mind.
url:                 http://matthewdiiulio.github.io
paginate:            1
baseurl:             "http://matthewdiiulio.github.io"

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Matthew DiIulio
  url:               https://twitter.com/matthewdiiulio
  email:             matthew@diiulio.org

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/poole/poole

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-sitemap
  - jemoji
